sudo: required
dist: trusty
language: cpp
compiler:
    - clang
    - g++
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6

script:
  - mkdir build
  - cd build
  - cmake .. && make